### ISSUE TITLE
Integration tests are inconsistent

### ISSUE THREAD

**Issue by JonatanMartens** [JonatanMartens/pyzeebe#66]
**Describe the bug**
Integration tests not always passing because of zeebe timeout.

**Comment by JonatanMartens** [comment]
Further information: 
When running the integration tests a zeebe standalone broker is started as a service with Github actions. Unfortunately, it takes Zeebe a while to get up and running, meaning that they occasionally fail due to:
`Time out between gateway and broker: Request type command-api-1 timed out in 15000 milliseconds`

**Comment by kbakk** [comment]
Was this fixed with #71? It seems like the merge commit failed again for test `tests/integration/integration_test.py::test_run_workflow_with_result`. 

Is it just this test that's flaky? Since its integration tests, having tests succeed 100% of the time may not be realistic. We could add `@pytest.mark.flaky(reruns=3)` on the test (or the module if there's several in the same module that fails) with [pytest-rerunfailures](https://github.com/pytest-dev/pytest-rerunfailures). 

There's a [few other options](https://docs.pytest.org/en/stable/flaky.html) but that seemed most popular.

Not saying to not address flaky tests, but in order to get a stable CI result it could be an alternative.

**Comment by JonatanMartens** [comment]
Thank you for bringing this to my attention!

It's not so much that the tests themselves are flaky, more so the environment in which they run. I thought that adding a health check to the zeebe container would fix this, but apparently not (or I implemented it incorrectly). 
There used to be a [wait action](https://github.com/marketplace/actions/wait-sleep ) of 30 seconds in the integration tests, but this caused them to be very slow.
My preferred option would be some way in which we can be certain that the zeebe container is up before we begin the tests.
