### ISSUE TITLE
Decide on patch vs MagicMock

### ISSUE THREAD

**Issue by JonatanMartens** [JonatanMartens/pyzeebe#69]
**Is your feature request related to a problem? Please describe.**
Currently, the tests are using two different ways of mocking (`patch` and `MagicMock`). 

**Describe the solution you'd like**
There needs to be a decision on which mock to use. We should look into which suits the project better.

**Comment by kbakk** [comment]
I think these cover different use cases. In both cases, a `MagicMock` object is passed to the code under test.

https://github.com/JonatanMartens/pyzeebe/blob/4202906527cd989ac80ba738dbb81f20ebf58ff0/tests/unit/grpc_internals/zeebe_workflow_adapter_test.py#L33

Here the code is designed to allow replacing with an alternative implementation (`MagicMock`), so it's easy to swap it out.

https://github.com/JonatanMartens/pyzeebe/blob/f83e992ede6fb11e80ebb2cb460bd295b2307947/tests/unit/worker/task_handler_test.py#L111

Here it's not easy (?) to replace the `logger` object, so patch is used (in this case, pytests `caplog` could be used instead though, but that's another discussion).

I do find the `MagicMock` example cleaner - it's closer to the [dependency injection](https://en.wikipedia.org/wiki/Dependency_injection) pattern. But it's not always going to be easy to use this pattern. I've almost always resorted to using patch in my projects, but that's because I haven't been very aware of DI pattern before.
